### ISSUE TITLE
Fix translations / spellings <-- reply here

### ISSUE THREAD

**Issue by HelpMeRuth** [lupusInc/lupusInc.github.io#3]
reply to this thread to note broken language
template:
[  ] Section: Derp --> Solution
If you fixed it tick the box [*]

make changes in the "Spelling branch" when everything is finished I will merge it in to the master brach (see Pull requests for all changes) so be sure to only edit on that branch.
![image](https://user-images.githubusercontent.com/17945932/36993608-95e4b8f0-20ae-11e8-8b1f-f55396fd4279.png)
// Branch
![image](https://user-images.githubusercontent.com/17945932/36993626-a75dd742-20ae-11e8-9890-7c67b62a6352.png)
// changes

**Comment by mandarijngein** [comment]
Buss

**Comment by HelpMeRuth** [comment]
[   ] Algemeen: Alfa-paar / Alfa-mannetje / Alfa-vrouwtje --> Alfapaar / Alfamannetje / vrouwtje
[   ] Algemeen: Beta's --> Bèta's
[   ] Algemeen: Verminder het aantal "misschien" dat wordt gebruikt
[ * ] Terretorium en dieet: "..40 km/h halen, De roedel.." gaat in formatie --> "De" -> "de"
[ * ] Invloed op de natuur: Middeljarige --> jonge
